STARTING_STATS = { 
    "rifle":
    {
        "magazine_capacity": 60.3,
        "status_duration": 99.99,
        "critical_damage": 120,
        "ammo_maximum": 49.95,
        "multishot": 90.3,
        "recoil": 90,
        "zoom":59.99,
        "punch_through": 2.7,
        "puncture_damage": 90,
        "slash_damage": 119.97,
        "fire_rate_/_attack_speed": 60.03,
        "reload_speed": 99.9,
        "projectile_speed": 90,
        "impact_damage": 119.97,
        "base_damage_/_melee_damage": 165,
        "damage_vs_grineer": 45,
        "damage_vs_infested": 45,
        "damage_vs_corpus": 45,
        "heat_damage": 90,
        "toxin_damage": 90,
        "cold_damage": 90,
        "electric_damage": 90,
        "critical_chance":149.99,
        "status_chance":90,
    },
    "shotgun":
    {
        "magazine_capacity": 50,
        "status_duration": 99,
        "critical_damage": 90,
        "ammo_maximum": 90,
        "multishot": 119.7,
        "recoil": 90,
        "punch_through": 2.7,
        "puncture_damage": 119.97,
        "slash_damage": 90,
        "fire_rate_/_attack_speed": 89.1,
        "reload_speed": 49.45,
        "projectile_speed": 89.1,
        "impact_damage":119.97,
        "base_damage_/_melee_damage": 164.7,
        "damage_vs_grineer": 45,
        "damage_vs_infested": 45,
        "damage_vs_corpus": 45,
        "heat_damage": 90,
        "toxin_damage": 90,
        "cold_damage": 90,
        "electric_damage": 90,
        "critical_chance":90,
        "status_chance":90,
    },
    "pistol":
    {
        "magazine_capacity": 50,
        "status_duration": 99.99,
        "critical_damage": 90,
        "ammo_maximum": 90,
        "multishot": 119.7,
        "recoil": 90,
        "zoom": 80.1,
        "punch_through": 2.7,
        "puncture_damage": 119.97,
        "slash_damage": 119.97,
        "fire_rate_/_attack_speed": 74.7,
        "reload_speed": 50,
        "projectile_speed": 90,
        "impact_damage":119.97,
        "base_damage_/_melee_damage": 219.6,
        "damage_vs_grineer": 45,
        "damage_vs_infested": 45,
        "damage_vs_corpus": 45,
        "heat_damage": 90,
        "toxin_damage": 90,
        "cold_damage": 90,
        "electric_damage": 90,
        "critical_chance":149.99,
        "status_chance":90,
    },
    "melee":
    {
        "status_duration": 99,
        "critical_damage": 90,
        "puncture_damage": 119.97,
        "slash_damage": 119.97,
        "fire_rate_/_attack_speed": 54.9,
        "impact_damage":119.97,
        "base_damage_/_melee_damage": 164.7,
        "damage_vs_grineer":45,
        "damage_vs_infested": 45,
        "damage_vs_corpus": 45,
        "heat_damage": 90,
        "toxin_damage": 90,
        "cold_damage": 90,
        "electric_damage": 90,
        "critical_chance": 180,
        "status_chance":90,
        "range":1.94,
        "combo_duration": 8.1,
        "channeling_damage": 24.5,
        "finisher_damage": 119.7,
        "critical_chance_on_slide_attack": 120,
        "chance_to_gain_extra_combo_count": 58.77,
        "channeling_efficiency": 73.44,
    },

    "archgun":
    {
        "magazine_capacity": 60.3,
        "status_duration": 99.99,
        "critical_damage": 80.1,
        "ammo_maximum": 99.9,
        "multishot": 60.3,
        "recoil": 90,
        "zoom": 59.99,
        "punch_through": 2.7,
        "puncture_damage": 119.97,
        "slash_damage": 119.97,
        "fire_rate_/_attack_speed": 60.03,
        "reload_speed": 50,
        "projectile_speed": 90,
        "impact_damage": 90,
        "base_damage_/_melee_damage": 99.9,
        "damage_vs_grineer": 45,
        "damage_vs_infested": 45,
        "damage_vs_corpus": 45,
        "heat_damage": 119.7,
        "toxin_damage": 119.7,
        "cold_damage": 119.7,
        "electric_damage": 119.7,
        "critical_chance":99.9,
        "status_chance":60.3,
    }
}